# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45fa9718bf8f21df896c55d19b5074c352f716bec92d71f079a2d9ed613cefe8c9a4bcea4fb05ea9b0910f7f9eff7ccd0a7b4d89074a29cf11c554e2a23aae74

test:
  secret_key_base: 390c7323d7fedb59d4c828b004bac08906a56d22c17a47baff27a260f2c0d5158d1eb88ad7b3900d028d7a8fb81a3a2429fec0ce3238143179e01bc2b5577548

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
